version: '3.8'
services:
  crawler_scheduler:
    # Set the image
    image: linsamtw/class01_crawler:dev
    # Set the hostname, used for display in Flower
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    # Command to start the worker
    command: pipenv run python fin_engine/scheduler
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        max_replicas_per_node: 1
        constraints: [node.labels.crawler_scheduler == true]
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network

networks:
  my_network:
    # Join an existing network
    external: true
