version: '3.8'
services:
  crawler_twse:
    # Set the image
    image: linsamtw/class01_crawler:dev
    # Set the hostname, used for display in Flower
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    # Command to start the worker
    command: pipenv run celery -A fin_engine.worker worker --loglevel=info --concurrency=1 --hostname=%h.twse -Q twse
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        # Limit to one instance per node to avoid IP bans from the exchange
        max_replicas_per_node: 1
        # Only deploy on nodes with the label crawler_twse=true
        constraints: [node.labels.crawler_twse == true]
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network

  crawler_tpex:
    # Set the image
    image: linsamtw/class01_crawler:dev
    # Set the hostname, used for display in Flower
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    # Command to start the worker
    command: pipenv run celery -A fin_engine.worker worker --loglevel=info --concurrency=1 --hostname=%h.tpex -Q tpex
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        # Limit to one instance per node to avoid IP bans from the exchange
        max_replicas_per_node: 1
        # Only deploy on nodes with the label crawler_tpex=true
        constraints: [node.labels.crawler_tpex == true]
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network

  crawler_taifex:
    # Set the image
    image: linsamtw/class01_crawler:dev
    # Set the hostname, used for display in Flower
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    # Command to start the worker
    command: pipenv run celery -A fin_engine.worker worker --loglevel=info --concurrency=1 --hostname=%h.taifex -Q taifex
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        # Limit to one instance per node to avoid IP bans from the exchange
        max_replicas_per_node: 1
        # Only deploy on nodes with the label crawler_taifex=true
        constraints: [node.labels.crawler_taifex == true]
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network

networks:
  my_network:
    # Join an existing network
    external: true
