version: '3.2'
services:

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # Map internal ports 5672 and 15672 to the same ports on the host
      - target: 5672
        published: 5672
        mode: host
      - target: 15672
        published: 15672
        mode: host
    environment:
      RABBITMQ_DEFAULT_USER: "worker"
      RABBITMQ_DEFAULT_PASS: "worker"
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - my_network

  flower:
    image: mher/flower:0.9.5
    command: ["flower", "--broker=amqp://worker:worker@rabbitmq", "--port=5555"]
    ports:
      # Map internal port 5555 to the same port on the host
      - target: 5555
        published: 5555
        mode: host
    depends_on:
      - rabbitmq
    networks:
      - my_network

networks:
  my_network:
